import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Gloock } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const gloock = Gloock({
  variable: "--font-gloock",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gloock.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
